# Custom Language File for Launcher Customizer

[ejs.app]
title = "WordSmp Launcher"

[ejs.landing]
mediaGitHubURL = "https://v3.wordsmp.com"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/Pp7XTNuVqv"

[ejs.settings]
sourceGithubLink = "https://github.com/WordcraftV/WordSmpLauncherv3"
supportLink = "https://github.com/WordcraftV/WordSmpLauncherv3/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue dans l'aventure WordSmp"
welcomeDescription = "La mission du serveur est de réunir des gens qui veulent juste jouer sans prise de tête avec des changements réguliers et des mises à jour performantes"
welcomeDescCTA = "Tu n'es qu'à quelques clics de rejoindre le serveur."
